services:
  app:
    image: ghcr.io/sondregronas/taafis:latest
    ports:
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WEBHOOK_SECRET=secret
    restart: unless-stopped
